// Liste des secteurs LinkedIn en français (id -> libellé).
// Figée depuis la taxonomie Unipile (/search/parameters?type=INDUSTRY) le 26/06/2026,
// récupérée via un compte FR. On la garde en local pour afficher TOUJOURS du
// français quelle que soit la langue du compte LinkedIn (la langue renvoyée par
// l API n est ni fiable ni forçable). Le filtre de recherche utilise l id,
// qui est indépendant de la langue.
export type Industry = { id: string; title: string };

export const INDUSTRIES: Industry[] = [
  { id: "50", title: "Activités d’architecture" },
  { id: "33", title: "Activités liées au sport" },
  { id: "3124", title: "Actualité en ligne" },
  { id: "2374", title: "Administration et planification du développement urbain et rural" },
  { id: "75", title: "Administration publique" },
  { id: "1737", title: "Agences et courtiers d’assurances" },
  { id: "1770", title: "Agents et courtiers immobiliers" },
  { id: "63", title: "Agriculture" },
  { id: "201", title: "Agriculture, sylviculture et pêche" },
  { id: "3131", title: "Applications mobiles de jeux" },
  { id: "3246", title: "Architecture et design accessibles" },
  { id: "38", title: "Artistes et écrivains" },
  { id: "39", title: "Arts du spectacle vivant" },
  { id: "2130", title: "Arts et sports de spectacle" },
  { id: "28", title: "Arts, spectacles et activités récréatives" },
  { id: "1909", title: "Associations sectorielles" },
  { id: "42", title: "Assurances" },
  { id: "45", title: "Banques d’investissement" },
  { id: "1713", title: "Bourses de valeurs mobilières et matières premières" },
  { id: "13", title: "Cabinets médicaux" },
  { id: "2063", title: "Centres de soins ambulatoires" },
  { id: "131", title: "Collecte de fonds caritatifs" },
  { id: "1981", title: "Collecte des déchets" },
  { id: "27", title: "Commerce de détail" },
  { id: "22", title: "Commerce de détail alimentaire" },
  { id: "1431", title: "Commerce de détail de biens d’occasion" },
  { id: "1370", title: "Commerce de détail de carburants" },
  { id: "1423", title: "Commerce de détail de fleurs" },
  { id: "111", title: "Commerce de détail de fournitures artistiques" },
  { id: "1409", title: "Commerce de détail de livres, journaux et magazines" },
  { id: "138", title: "Commerce de détail de machines et d’équipements de bureau" },
  { id: "1324", title: "Commerce de détail de matériaux de construction et matériel de jardinage" },
  { id: "1309", title: "Commerce de détail de meubles et articles d’ameublement" },
  { id: "1339", title: "Commerce de détail de produits alimentaires et boissons" },
  { id: "1359", title: "Commerce de détail de produits pharmaceutiques, de parfums et de produits de beauté" },
  { id: "1292", title: "Commerce de détail de véhicules automobiles" },
  { id: "1319", title: "Commerce de détail d’appareils électriques et électroniques" },
  { id: "143", title: "Commerce de détail d’articles de luxe et de bijouterie" },
  { id: "1424", title: "Commerce de détail d’articles de papeterie et cadeaux" },
  { id: "19", title: "Commerce de détail d’habillement et d’accessoires de mode" },
  { id: "1407", title: "Commerce de détail d’instruments de musique et de partitions musicales" },
  { id: "133", title: "Commerce de gros" },
  { id: "1267", title: "Commerce de gros de boissons alcoolisées" },
  { id: "1230", title: "Commerce de gros de chaussures" },
  { id: "49", title: "Commerce de gros de matériaux de construction" },
  { id: "1206", title: "Commerce de gros de matériaux recyclables" },
  { id: "1171", title: "Commerce de gros de matériel électrique et électronique" },
  { id: "1153", title: "Commerce de gros de matériels photographiques" },
  { id: "1137", title: "Commerce de gros de meubles et articles d’ameublement" },
  { id: "1166", title: "Commerce de gros de minerais et métaux" },
  { id: "1212", title: "Commerce de gros de papier et d’articles de papeterie" },
  { id: "1250", title: "Commerce de gros de produits agricoles bruts" },
  { id: "1231", title: "Commerce de gros de produits alimentaires et boissons" },
  { id: "1257", title: "Commerce de gros de produits chimiques et autres produits intermédiaires" },
  { id: "1262", title: "Commerce de gros de produits pétroliers" },
  { id: "1221", title: "Commerce de gros de préparations pharmaceutiques" },
  { id: "1178", title: "Commerce de gros de quincaillerie et fournitures pour plomberie et chauffage" },
  { id: "1128", title: "Commerce de gros de véhicules automobiles et pièces détachées" },
  { id: "1208", title: "Commerce de gros d’articles de joaillerie et bijouterie" },
  { id: "1222", title: "Commerce de gros d’habillement et de textiles" },
  { id: "1157", title: "Commerce de gros d’ordinateurs et d’équipements informatiques" },
  { id: "1187", title: "Commerce de gros d’équipements industriels" },
  { id: "134", title: "Commerce de gros import-export" },
  { id: "141", title: "Commerce et développement international" },
  { id: "1725", title: "Compagnies d’assurances" },
  { id: "47", title: "Comptabilité" },
  { id: "123", title: "Conseil en externalisation et délocalisation" },
  { id: "1720", title: "Conseil en investissement" },
  { id: "2401", title: "Conseil opérationnel" },
  { id: "48", title: "Construction" },
  { id: "406", title: "Construction de bâtiments" },
  { id: "413", title: "Construction de bâtiments non résidentiels" },
  { id: "408", title: "Construction de bâtiments résidentiels" },
  { id: "62", title: "Construction de matériel ferroviaire" },
  { id: "431", title: "Construction de routes, autoroutes et ponts" },
  { id: "419", title: "Construction des services publics de distribution" },
  { id: "58", title: "Construction navale" },
  { id: "3126", title: "Design d’intérieur" },
  { id: "140", title: "Design graphique" },
  { id: "3256", title: "Design régénératif" },
  { id: "106", title: "Directeurs du capital-risque et du capital-investissement" },
  { id: "397", title: "Distribution de gaz naturel" },
  { id: "1002", title: "Distribution de Pièces" },
  { id: "404", title: "Distribution de vapeur et d’air conditionné" },
  { id: "3252", title: "Données et analyses climatiques" },
  { id: "2217", title: "Débits de boissons" },
  { id: "2391", title: "Défense et affaires étrangères" },
  { id: "4", title: "Développement de logiciels" },
  { id: "3102", title: "Développement de logiciels personnalisés de systèmes informatiques" },
  { id: "3251", title: "Développement de technologies climatiques" },
  { id: "121", title: "Enquêtes et sécurité" },
  { id: "1738", title: "Enquêteurs d’assurances et services actuariels" },
  { id: "1999", title: "Enseignement" },
  { id: "2027", title: "Enseignement de disciplines sportives et d’activités de loisirs" },
  { id: "2025", title: "Enseignement des beaux-arts" },
  { id: "67", title: "Enseignement primaire et secondaire" },
  { id: "68", title: "Enseignement supérieur" },
  { id: "93", title: "Entreposage et stockage" },
  { id: "2247", title: "Entretien de machines commerciales et industrielles" },
  { id: "3103", title: "Exploitation et maintenance de systèmes informatiques" },
  { id: "3096", title: "Extraction de gaz naturel" },
  { id: "3095", title: "Extraction de pétrole" },
  { id: "142", title: "Fabrication de boissons" },
  { id: "703", title: "Fabrication de caoutchouc et fibres synthétiques" },
  { id: "52", title: "Fabrication de composants pour l’industrie aéronautique et aérospatiale" },
  { id: "3254", title: "Fabrication de compteurs intelligents" },
  { id: "55", title: "Fabrication de machines" },
  { id: "901", title: "Fabrication de machines agricoles et forestières, pour l’extraction ou la construction" },
  { id: "147", title: "Fabrication de machines d’automatisation" },
  { id: "135", title: "Fabrication de machines industrielles" },
  { id: "928", title: "Fabrication de machines pour la métallurgie" },
  { id: "918", title: "Fabrication de machines pour le commerce et les industries de services" },
  { id: "1095", title: "Fabrication de matelas et stores" },
  { id: "1029", title: "Fabrication de matériel de transport" },
  { id: "3245", title: "Fabrication de matériel informatique d’accessibilité" },
  { id: "1090", title: "Fabrication de meubles de bureau et de magasin" },
  { id: "26", title: "Fabrication de meubles et d’articles d’ameublement" },
  { id: "1080", title: "Fabrication de meubles pour particuliers et institutions" },
  { id: "935", title: "Fabrication de moteurs, génératrices et transformateurs électriques et de matériel de distribution et de commande électrique" },
  { id: "61", title: "Fabrication de papier et de produits en papier" },
  { id: "18", title: "Fabrication de parfums et de produits pour la toilette" },
  { id: "3255", title: "Fabrication de piles à combustible" },
  { id: "876", title: "Fabrication de pièces tournées et d’éléments de fixation" },
  { id: "23", title: "Fabrication de produits alimentaires et boissons" },
  { id: "54", title: "Fabrication de produits chimiques" },
  { id: "529", title: "Fabrication de produits de boulangerie-pâtisserie et de pâtes alimentaires" },
  { id: "784", title: "Fabrication de produits en bois" },
  { id: "763", title: "Fabrication de produits en caoutchouc" },
  { id: "743", title: "Fabrication de produits en caoutchouc et en plastique" },
  { id: "117", title: "Fabrication de produits en plastique" },
  { id: "24", title: "Fabrication de produits informatiques et électroniques" },
  { id: "65", title: "Fabrication de produits laitiers" },
  { id: "15", title: "Fabrication de produits pharmaceutiques" },
  { id: "873", title: "Fabrication de ressorts et de produits en fil métallique" },
  { id: "3247", title: "Fabrication de robots" },
  { id: "7", title: "Fabrication de semi-conducteurs" },
  { id: "871", title: "Fabrication de serrures et de ferrures" },
  { id: "495", title: "Fabrication de sucre et produits de confiserie" },
  { id: "994", title: "Fabrication de supports magnétiques et optiques" },
  { id: "21", title: "Fabrication de tabac" },
  { id: "60", title: "Fabrication de textiles" },
  { id: "887", title: "Fabrication de valves, billes et cylindres en métal" },
  { id: "779", title: "Fabrication de verre et d’articles en verre" },
  { id: "145", title: "Fabrication de verre, de produits céramiques et de ciment" },
  { id: "53", title: "Fabrication de véhicules automobiles" },
  { id: "615", title: "Fabrication d’accessoires de mode" },
  { id: "998", title: "Fabrication d’appareils d’éclairage électrique" },
  { id: "1005", title: "Fabrication d’appareils électroménagers" },
  { id: "112", title: "Fabrication d’appareils électroménagers, électriques et électroniques" },
  { id: "20", title: "Fabrication d’articles de sport" },
  { id: "146", title: "Fabrication d’emballages et conteneurs" },
  { id: "983", title: "Fabrication d’instruments de mesure et de contrôle" },
  { id: "3", title: "Fabrication d’ordinateurs et d’équipements périphériques" },
  { id: "852", title: "Fabrication d’éléments en métal pour la construction" },
  { id: "973", title: "Fabrication d’équipements audio et vidéo" },
  { id: "1042", title: "Fabrication d’équipements automobiles" },
  { id: "923", title: "Fabrication d’équipements aérauliques et frigorifiques" },
  { id: "964", title: "Fabrication d’équipements de communication" },
  { id: "17", title: "Fabrication d’équipements médicaux" },
  { id: "3241", title: "Fabrication d’équipements pour les énergies renouvelables" },
  { id: "2468", title: "Fabrication d’équipements électriques" },
  { id: "1", title: "Fabrication pour l’aérospatiale et la défense" },
  { id: "2020", title: "Formation au pilotage" },
  { id: "3105", title: "Formation et assistance en systèmes informatiques" },
  { id: "2018", title: "Formation technique et professionnelle" },
  { id: "2366", title: "Gestion de programmes portant sur l’air, les eaux et les déchets" },
  { id: "46", title: "Gestion des investissements" },
  { id: "3086", title: "Gestion des services publics de distribution" },
  { id: "51", title: "Génie civil" },
  { id: "14", title: "Hôpitaux et services de santé" },
  { id: "31", title: "Hôtellerie" },
  { id: "44", title: "Immobilier" },
  { id: "128", title: "Immobilier non résidentiel locatif" },
  { id: "1759", title: "Immobilier résidentiel locatif" },
  { id: "25", title: "Industrie manufacturière" },
  { id: "57", title: "Industrie pétrolière et gazière" },
  { id: "332", title: "Industries extractives" },
  { id: "2458", title: "Infrastructure de données et data analytics" },
  { id: "3248", title: "Ingénierie robotique" },
  { id: "3104", title: "Installation et suppression de systèmes informatiques" },
  { id: "40", title: "Installations sportives, récréatives et de loisirs" },
  { id: "1530001", title: "Intelligence artificielle" },
  { id: "109", title: "Jeux vidéo" },
  { id: "2069", title: "Laboratoires d’analyses médicales" },
  { id: "1798", title: "Location d’équipements commerciaux et industriels" },
  { id: "3186", title: "Marchands d’art" },
  { id: "129", title: "Marchés des capitaux" },
  { id: "120", title: "Modes alternatifs de règlement des conflits" },
  { id: "113", title: "Médias audio et vidéo en ligne" },
  { id: "3133", title: "Médias et télécommunications" },
  { id: "807", title: "Métallurgie" },
  { id: "1517", title: "Navettes et services de transport pour personnes à mobilité réduite" },
  { id: "3250", title: "Officines de pharmacie" },
  { id: "1644", title: "Opérateurs de télécommunications" },
  { id: "30", title: "Organisation de voyages" },
  { id: "90", title: "Organisations civiques et sociales" },
  { id: "107", title: "Organisations politiques" },
  { id: "1911", title: "Organisations professionnelles" },
  { id: "100", title: "Organisations à but non lucratif" },
  { id: "2167", title: "Parcs d’attractions et salles de jeux" },
  { id: "136", title: "Photographie" },
  { id: "1285", title: "Plateformes de marché en ligne" },
  { id: "3127", title: "Plateformes de réseaux sociaux" },
  { id: "3128", title: "Plateformes d’informatique décisionnelle" },
  { id: "126", title: "Production audiovisuelle" },
  { id: "564", title: "Production de boissons alcooliques distillées" },
  { id: "383", title: "Production d’électricité" },
  { id: "389", title: "Production d’électricité géothermique" },
  { id: "386", title: "Production d’électricité nucléaire" },
  { id: "390", title: "Production d’électricité par biomasse" },
  { id: "387", title: "Production d’électricité solaire" },
  { id: "2489", title: "Production d’électricité éolienne" },
  { id: "384", title: "Production d’énergie hydroélectrique" },
  { id: "385", title: "Production d’énergie à partir de combustibles fossiles" },
  { id: "3240", title: "Production d’énergies renouvelables" },
  { id: "36", title: "Production et distribution de médias audiovisuels" },
  { id: "5", title: "Produits de réseaux informatiques" },
  { id: "3130", title: "Produits logiciels de sécurité des données" },
  { id: "3100", title: "Produits logiciels d’informatique mobile" },
  { id: "3099", title: "Produits logiciels embarqués" },
  { id: "3101", title: "Produits logiciels informatiques pour ordinateurs" },
  { id: "2368", title: "Programmes de conservation de l’environnement" },
  { id: "388", title: "Programmes de qualité environnementale" },
  { id: "69", title: "Programmes d’administration de l’éducation" },
  { id: "2360", title: "Programmes d’aide sociale" },
  { id: "3085", title: "Programmes relatifs aux transports" },
  { id: "66", title: "Pêche" },
  { id: "12", title: "Recherche en biotechnologie" },
  { id: "114", title: "Recherche en nanotechnologie" },
  { id: "3089", title: "Recherche et technologie spatiales" },
  { id: "104", title: "Recrutement et placement de personnel" },
  { id: "2253", title: "Réfection de tissus d’ameublement et réparation de meubles" },
  { id: "2255", title: "Réparation de chaussures et d’articles en cuir" },
  { id: "2240", title: "Réparation et entretien de matériel électronique et de précision" },
  { id: "1530002", title: "Réseaux sociaux/Médias sociaux" },
  { id: "29", title: "Salles de jeux d’argent et casinos" },
  { id: "2353", title: "Santé et services sociaux" },
  { id: "2358", title: "Santé publique" },
  { id: "1916", title: "Services administratifs" },
  { id: "2282", title: "Services aux animaux de compagnie" },
  { id: "91", title: "Services aux consommateurs" },
  { id: "41", title: "Services bancaires" },
  { id: "124", title: "Services de bien-être et installations sportives" },
  { id: "2272", title: "Services de blanchisserie et de pressing" },
  { id: "3134", title: "Services de blockchain" },
  { id: "2259", title: "Services de coiffure et soins de beauté" },
  { id: "1855", title: "Services de conception de systèmes informatiques" },
  { id: "2258", title: "Services de conciergerie et services personnels" },
  { id: "86", title: "Services de conseil en environnement" },
  { id: "99", title: "Services de design" },
  { id: "3106", title: "Services de données de systèmes informatiques" },
  { id: "398", title: "Services de gestion des eaux, eaux usées, vapeur et climatisation" },
  { id: "102", title: "Services de gestion stratégique" },
  { id: "148", title: "Services de lobbying" },
  { id: "1779", title: "Services de location de biens matériels" },
  { id: "3070", title: "Services de lutte contre les incendies" },
  { id: "1862", title: "Services de marketing" },
  { id: "1965", title: "Services de nettoyage et d’entretien" },
  { id: "3257", title: "Services de pompes funèbres" },
  { id: "80", title: "Services de publicité" },
  { id: "70", title: "Services de recherche" },
  { id: "1923", title: "Services de recrutement de cadres" },
  { id: "98", title: "Services de relations publiques et communication" },
  { id: "137", title: "Services de ressources humaines" },
  { id: "34", title: "Services de restauration" },
  { id: "2214", title: "Services de restauration mobile" },
  { id: "2074", title: "Services de santé à domicile" },
  { id: "1958", title: "Services de systèmes de sécurité" },
  { id: "1925", title: "Services des agences de travail temporaire" },
  { id: "3244", title: "Services d’accessibilité numérique" },
  { id: "73", title: "Services d’administration de la justice" },
  { id: "1956", title: "Services d’agents de sécurité et de surveillance" },
  { id: "2125", title: "Services d’aide à l’insertion professionnelle" },
  { id: "2934", title: "Services d’aménagement paysager" },
  { id: "3249", title: "Services d’arpentage et de cartographie" },
  { id: "2190", title: "Services d’hébergement et de restauration" },
  { id: "2091", title: "Services d’hébergement médicalisé" },
  { id: "83", title: "Services d’impression" },
  { id: "84", title: "Services d’information" },
  { id: "3242", title: "Services d’ingénierie" },
  { id: "2122", title: "Services d’urgence et d’assistance" },
  { id: "11", title: "Services et conseil aux entreprises" },
  { id: "96", title: "Services et conseil en informatique" },
  { id: "76", title: "Services exécutifs" },
  { id: "43", title: "Services financiers" },
  { id: "3258", title: "Services funéraires" },
  { id: "1757", title: "Services immobiliers et de location de biens matériels" },
  { id: "10", title: "Services juridiques" },
  { id: "72", title: "Services législatifs" },
  { id: "3243", title: "Services pour les énergies renouvelables" },
  { id: "59", title: "Services publics de distribution" },
  { id: "79", title: "Services publics généraux" },
  { id: "122", title: "Services relatifs aux bâtiments" },
  { id: "16", title: "Services vétérinaires" },
  { id: "88", title: "Services à la personne" },
  { id: "139", title: "Soins de santé mentale" },
  { id: "298", title: "Sylviculture et exploitation forestière" },
  { id: "78", title: "Sécurité civile" },
  { id: "118", title: "Sécurité informatique et des réseaux" },
  { id: "3259", title: "Technologie énergétique" },
  { id: "6", title: "Technologie, information et Internet" },
  { id: "1594", title: "Technologie, médias et télécommunications" },
  { id: "3107", title: "Tests et évaluation de systèmes informatiques" },
  { id: "108", title: "Traduction et localisation linguistique" },
  { id: "400", title: "Traitement et distribution d’eau" },
  { id: "1986", title: "Traitement et élimination des déchets" },
  { id: "883", title: "Traitements des métaux" },
  { id: "382", title: "Transmission, contrôle et distribution d’énergie électrique" },
  { id: "94", title: "Transport aérien" },
  { id: "1481", title: "Transport ferroviaire" },
  { id: "95", title: "Transport maritime" },
  { id: "1520", title: "Transport par conduites" },
  { id: "116", title: "Transport, logistique, chaîne logistique et stockage" },
  { id: "87", title: "Transports de fret et de colis" },
  { id: "92", title: "Transports routiers de fret" },
  { id: "1512", title: "Transports scolaires et de personnel" },
  { id: "1495", title: "Transports terrestres de voyageurs" },
  { id: "1532", title: "Transports touristiques" },
  { id: "1497", title: "Transports urbains et suburbains de voyageurs" },
  { id: "435", title: "Travaux de construction spécialisés" },
  { id: "460", title: "Travaux de finition de bâtiment" },
  { id: "436", title: "Travaux de maçonnerie générale et gros œuvre de bâtiment" },
  { id: "1001", title: "Travaux Publics" },
  { id: "8", title: "Télécommunications" },
  { id: "1649", title: "Télécommunications par satellite" },
  { id: "119", title: "Télécommunications sans fil" },
  { id: "1445", title: "Vente à distance" },
  { id: "81", title: "Édition de journaux" },
  { id: "1602", title: "Édition de livres" },
  { id: "82", title: "Édition de livres et périodiques" },
  { id: "1625", title: "Édition de partitions musicales" },
  { id: "1600", title: "Édition de périodiques" },
  { id: "3132", title: "Édition en ligne" },
  { id: "64", title: "Élevage bovin" },
  { id: "256", title: "Élevage et pêche" },
  { id: "2142", title: "Équipes et clubs de sport" },
  { id: "110", title: "Événementiel" },
];
